---
- name: add key
  apt_key: keyserver=keyserver.ubuntu.com id=9ECBEC467F0CEB10 state=present

- name: app repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present

- name: install
  apt: name={{ item }} state=present
  with_items:
    - mongodb-org

- name: configure mongod.conf
  template:
    src=mongod.conf.j2
    dest=/etc/mongod.conf
  notify:
      - restart mongodb

- name: wait for mongod
  wait_for: port={{mongodb.config.net.port}}

- name: copy user script
  template:
    src=createuser.js.j2
    dest=/tmp/createuser.js

- name: add admin user
  command: mongo --shell /tmp/createuser.js

- name: copy .mongorc.js file for user root
  template:
    src=user-mongorc.js.j2
    dest=/root/.mongorc.js
    owner=root
    group=root
    mode=0600

- name: copy .mongorc.js for user vagrant
  template:
    src=user-mongorc.js.j2
    dest=/home/vagrant/.mongorc.js
    owner=vagrant
    group=vagrant
    mode=0600
